import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full min-h-full bg-transparent antialiased`}
    >
      <body className="relative min-h-full">
        {/* Body paints bg-nature.jpg; keep this wrapper above base paint, below modals */}
        <div className="relative z-[10] flex min-h-full flex-col bg-transparent">{children}</div>
      </body>
    </html>
  );
}
